### ISSUE TITLE
Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by silverwind** [thomaspoignant/homebrew-tap#1]
Using Homebrew 3.3.1 on macOS 12, I observe this warning:

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the thomaspoignant/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/thomaspoignant/homebrew-tap/api-scenario.rb:6
````

**Comment by thomaspoignant** [comment]
Oh thanks for the report, I will check the issue a soon as I have some time to work on it.

**Comment by thomaspoignant** [comment]
Thanks it was resolved by the commit https://github.com/thomaspoignant/homebrew-tap/commit/e59153be77b0bfa33d67c2168c857f8396f9fbf7

**Comment by silverwind** [comment]
Thanks, you should probably also update the other formula at https://github.com/thomaspoignant/homebrew-tap/blob/master/yamllint-checkstyle.rb 😉

**Comment by thomaspoignant** [comment]
Oh yes, you are right, I've forgotten that I had this tap also 🤕
